___

<a href='http://www.pieriandata.com'><img src='../Pierian_Data_Logo.png'/></a>
___
<center><em>Copyright by Pierian Data Inc.</em></center>
<center><em>For more information, visit us at <a href='http://www.pieriandata.com'>www.pieriandata.com</a></em></center>

# Linear Regression Project Exercise

Now that we have learned about feature engineering, cross validation, and grid search, let's test all your new skills with a project exercise in Machine Learning. This exercise will have a more guided approach, later on the ML projects will begin to be more open-ended. We'll start off with using the final version of the Ames Housing dataset we worked on through the feature engineering section of the course. Your goal will be to create a Linear Regression Model, train it on the data with the optimal parameters using a grid search, and then evaluate the model's capabilities on a test set.

---
---
---
## Complete the tasks in bold

**TASK: Run the cells under the Imports and Data section to make sure you have imported the correct general libraries as well as the correct datasets. Later on you may need to run further imports from scikit-learn.**

### Imports

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Data

In [2]:
ls

 Volume in drive C is Windows
 Volume Serial Number is 4E2B-C9C8

 Directory of C:\Users\gmzyn\++++++€ALI�MALAR\jose_pandas

21.11.2022  05:00    <DIR>          .
05.11.2022  16:09    <DIR>          ..
21.11.2022  01:02    <DIR>          .ipynb_checkpoints
13.11.2022  20:14           123.494 00-Intro-to-Simple-Linear-Regression.ipynb
25.08.2022  20:09           565.403 00-Series.ipynb
08.06.2022  09:33           332.428 00-Sup-Learning-Capstone-Tree-Methods .ipynb
31.10.2022  03:41         1.082.915 01-Capstone-Project-Solutions .ipynb
26.08.2022  00:04           208.970 01-DataFrames.ipynb
13.11.2022  20:14           534.284 01-Linear-Regression-with-Scitkit-Learn.ipynb
13.10.2022  22:45         3.369.518 01-Sup-Learning-Capstone-Tree-Methods-SOLNs.ipynb
21.11.2022  05:00            80.686 02-Linear-Regression-Project-Exercise.ipynb
13.11.2022  20:14            66.745 02-Polynomial-Regression.ipynb
18.09.2022  06:35            62.840 06-Combining-DataFrames.ipynb
13.10.2022  03:59             7.431 all_sites_scores.csv
21.11.2022  01:32         1.793.682 AMES_Final_DF.csv
13.10.2022  21:38         2.269.934 Capstone-Project-jose.ipynb
31.08.2022  20:59            72.645 DataFrames.ipynb
18.09.2022  23:54                51 example.csv
19.09.2022  10:19             5.517 example.xlsx
13.10.2022  03:59            18.868 fandango_scrape.csv
09.06.2022  01:51            52.974 insurance.csv
09.06.2022  02:01            20.154 Insurance.csv.ipynb
12.06.2022  01:11            64.850 Insurance1.ipynb
13.11.2022  22:04    <DIR>          linear_regresyon
14.09.2022  22:52               177 movie_scores.csv
16.09.2022  11:56            17.727 mpg.csv
25.08.2022  00:58            10.825 my first plot.png
19.09.2022  09:48             5.022 my_excel_file.xlsx
19.09.2022  00:19                40 newfile.csv
25.08.2022  12:55           105.556 Numpy_videodan.ders.ipynb
12.06.2022  19:50         1.116.953 Pandas Serileri.ipynb
08.06.2022  11:12             6.575 pandas.w3sc_soru.ipynb
19.09.2022  22:04           942.188 Pandas_videodan.ders.ipynb
06.06.2022  22:51            29.117 Python Sorulari (1).ipynb
18.09.2022  21:17             5.459 RetailSales_BeerWineLiquor.csv
09.06.2022  13:32        16.239.776 Salaries.csv
19.09.2022  09:43             1.328 sample_table.html
15.10.2022  16:53    <DIR>          seaborn_jose
13.06.2022  22:21            72.771 SF Salaries Exercise- Solutions.ipynb
27.08.2022  10:34            18.752 tips.csv
12.06.2022  12:37           102.271 Tips_cvss.ipynb
              36 File(s)     29.407.926 bytes
               5 Dir(s)  338.317.762.560 bytes free

In [3]:
df = pd.read_csv("AMES_Final_DF.csv")

In [4]:
df.head()

,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
0,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,441.0,...,0,0,0,0,1,0,0,0,1,0
1,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,270.0,...,0,0,0,0,1,0,0,0,1,0
2,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,406.0,...,0,0,0,0,1,0,0,0,1,0
3,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,1045.0,...,0,0,0,0,1,0,0,0,1,0
4,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,137.0,...,0,0,0,0,1,0,0,0,1,0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2925 entries, 0 to 2924
Columns: 274 entries, Lot Frontage to Sale Condition_Partial
dtypes: float64(11), int64(263)
memory usage: 6.1 MB

In [9]:
df.columns

Index(['Lot Frontage', 'Lot Area', 'Overall Qual', 'Overall Cond',
       'Year Built', 'Year Remod/Add', 'Mas Vnr Area', 'BsmtFin SF 1',
       'BsmtFin SF 2', 'Bsmt Unf SF',
       ...
       'Sale Type_ConLw', 'Sale Type_New', 'Sale Type_Oth', 'Sale Type_VWD',
       'Sale Type_WD ', 'Sale Condition_AdjLand', 'Sale Condition_Alloca',
       'Sale Condition_Family', 'Sale Condition_Normal',
       'Sale Condition_Partial'],
      dtype='object', length=274)

In [10]:
df["SalePrice"]

0       215000
1       105000
2       172000
3       244000
4       189900
         ...
2920    142500
2921    131000
2922    132000
2923    170000
2924    188000
Name: SalePrice, Length: 2925, dtype: int64

**TASK: The label we are trying to predict is the SalePrice column. Separate out the data into X features and y labels**
__Tahmin etmeye çalıştığımız etiket SalePrice sütunudur. Verileri X özelliklerine ve y etiketlerine ayırın

In [11]:
X=df.drop("SalePrice",axis=1)
y=df["SalePrice"]

**TASK: Use scikit-learn to split up X and y into a training set and test set. Since we will later be using a Grid Search strategy, set your test proportion to 10%. To get the same data split as the solutions notebook, you can specify random_state = 101**

X ve y'yi bir eğitim seti ve test seti olarak ayırmak için scikit-learn'ü kullanın. Daha sonra bir Izgara Arama stratejisi kullanacağımız için test oranınızı %10 olarak ayarlayın. Çözüm not defteriyle aynı veri bölünmesini elde etmek için random_state = 101 belirtebilirsiniz.

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=101)

**TASK: The dataset features has a variety of scales and units. For optimal regression performance, scale the X features. Take carefuly note of what to use for .fit() vs what to use for .transform()**

GÖREV: Veri kümesi öznitelikleri çeşitli ölçeklere ve birimlere sahiptir. Optimum regresyon performansı için X özelliklerini ölçeklendirin. .fit() için ne kullanılacağına karşı .transform() için ne kullanılacağına dikkat edin.

In [14]:
#class sklearn.preprocessing.StandardScaler(*, copy=True, with_mean=True, with_std=True)

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
scaler = StandardScaler()

In [17]:
scaler.fit(X_train)

StandardScaler()

In [18]:
scaled_X_train=scaler.transform(X_train)
scaled_X_test=scaler.transform(X_test)

**TASK: We will use an Elastic Net model. Create an instance of default ElasticNet model with scikit-learn**

Bir Elastic Net modeli kullanacağız. scikit-learn ile varsayılan ElasticNet modelinin bir örneğini oluşturun

In [19]:
from sklearn.linear_model import ElasticNet

In [20]:
#help(ElasticNet)

In [21]:
base_elastic_model=ElasticNet(max_iter=1000000)

### GÖREV: Elastic Net modelinin alfa ve L1 oranı olmak üzere iki ana parametresi vardır. ElasticNet için bir sözlük parametre değerleri ızgarası oluşturun. Bu değerlerle oynamaktan çekinmeyin, unutmayın, çözüm seçenekleriyle tam olarak eşleşmeyebilirsiniz.

In [22]:
params_grid={"alpha":[0.1,1,5,10,50,100],
             "l1_ratio":[.1,.5,7,.95,.99,1]    }

**TASK: Using scikit-learn create a GridSearchCV object and run a grid search for the best parameters for your model based on your scaled training data. [In case you are curious about the warnings you may recieve for certain parameter combinations](https://stackoverflow.com/questions/20681864/lasso-on-sklearn-does-not-converge)**

GÖREV: scikit-learn'ü kullanarak bir GridSearchCV nesnesi oluşturun ve ölçekli eğitim verilerinize dayalı olarak modeliniz için en iyi parametreleri bulmak üzere bir ızgara araması yapın.

In [23]:
from sklearn.model_selection import GridSearchCV

In [24]:
Grid_model=GridSearchCV(estimator=base_elastic_model,
                       param_grid=params_grid,
                       scoring="neg_mean_squared_error",
                        cv=5,verbose=1)

In [26]:
Grid_model.fit(scaled_X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits

C:\anaconda\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 180.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\anaconda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py", line 925, in fit
    raise ValueError(
ValueError: l1_ratio must be between 0 and 1; got l1_ratio=7

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [-5.42228792e+08 -5.32948736e+08             nan -5.28239168e+08
 -5.32172106e+08 -5.43743273e+08 -7.29435328e+08 -6.39245312e+08
             nan -5.32814616e+08 -5.26836526e+08 -5.40926897e+08
 -1.37935930e+09 -1.04479328e+09             nan -5.80075610e+08
 -5.32244469e+08 -5.32231020e+08 -1.99787564e+09 -1.45655781e+09
             nan -6.39510636e+08 -5.43742909e+08 -5.29000215e+08
 -4.26119887e+09 -3.37993102e+09             nan -1.04811237e+09
 -6.40962442e+08 -5.19227651e+08 -5.14411280e+09 -4.41375045e+09
             nan -1.46464204e+09 -7.56590053e+08 -5.14792923e+08]
  warnings.warn(

GridSearchCV(cv=5, estimator=ElasticNet(max_iter=1000000),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 7, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=1)

**TASK: Display the best combination of parameters for your model**

In [27]:
Grid_model.best_estimator_

ElasticNet(alpha=100, l1_ratio=1, max_iter=1000000)

In [28]:
Grid_model.best_params_

{'alpha': 100, 'l1_ratio': 1}

{'alpha': 100, 'l1_ratio': 1}

**TASK: Evaluate your model's performance on the unseen 10% scaled test set. In the solutions notebook we achieved an MAE of $\$$14149 and a RMSE of $\$$20532**

Görünmeyen %10 ölçekli test setinde modelinizin performansını değerlendirin. Çözüm defterinde 14149 $ MAE ve 20532 $ RMSE elde ettik.

In [29]:
Grid_model.cv_results_

{'mean_fit_time': array([1.02364349e-01, 1.34641123e-01, 2.55265236e-03, 7.56265306e-01,
        2.22447915e+00, 5.36179676e+01, 8.38068485e-02, 1.02634048e-01,
        5.08127213e-03, 2.27158976e-01, 5.64660549e-01, 8.55559149e+00,
        5.72993755e-02, 4.29255009e-02, 5.94420433e-03, 9.60025311e-02,
        1.83033276e-01, 3.87076559e+00, 2.90362835e-02, 2.93184280e-02,
        5.47804832e-03, 7.38440037e-02, 1.08846045e-01, 2.34583206e+00,
        2.50416279e-02, 2.47055531e-02, 4.53610420e-03, 3.58660698e-02,
        6.86488628e-02, 5.32534313e-01, 2.34908104e-02, 2.42575169e-02,
        5.52487373e-03, 3.18170071e-02, 4.97869492e-02, 2.98176575e-01]),
 'std_fit_time': array([3.59691638e-03, 6.19367975e-03, 4.61328519e-04, 2.62715932e-02,
        3.51716307e-01, 2.45661588e+01, 2.17928555e-03, 4.54426186e-03,
        3.49010879e-04, 2.80270161e-03, 2.37359734e-02, 1.30065573e+00,
        3.87494733e-02, 2.33773089e-03, 5.55572638e-04, 2.29453964e-03,
        9.47663911e-03, 1.15793043e+00, 2.19553229e-03, 2.20887886e-03,
        4.63606202e-04, 4.91125380e-03, 5.02002648e-03, 1.17373653e-01,
        2.82423954e-03, 2.76482687e-03, 5.62556818e-04, 2.37376574e-03,
        2.29133160e-03, 3.76099297e-02, 2.74336358e-03, 2.26462662e-03,
        3.19189750e-04, 1.41975665e-03, 3.25970268e-03, 1.68702500e-02]),
 'mean_score_time': array([0.00080314, 0.0009016 , 0.        , 0.00069909, 0.00062523,
        0.00192156, 0.00111356, 0.00110183, 0.        , 0.00168171,
        0.0019474 , 0.00160527, 0.00187879, 0.0016448 , 0.        ,
        0.00120916, 0.00201011, 0.00215268, 0.00142484, 0.00130734,
        0.        , 0.00197582, 0.00161319, 0.00163517, 0.00130301,
        0.00183983, 0.        , 0.00172529, 0.00160909, 0.00160494,
        0.0016243 , 0.00144558, 0.        , 0.00119581, 0.00188642,
        0.00159369]),
 'std_score_time': array([4.01744647e-04, 6.58411796e-04, 0.00000000e+00, 3.97907092e-04,
        3.69094834e-04, 4.82890629e-04, 6.82549872e-04, 2.03464946e-04,
        0.00000000e+00, 4.85798378e-04, 5.21058991e-04, 4.97920886e-04,
        4.00036520e-04, 6.16352606e-04, 0.00000000e+00, 3.92854458e-04,
        2.12591311e-05, 2.23054922e-04, 4.93333000e-04, 3.93613249e-04,
        0.00000000e+00, 4.25128190e-04, 4.68214911e-04, 5.27517571e-04,
        3.99916630e-04, 5.07126336e-04, 0.00000000e+00, 5.14706223e-04,
        4.68957333e-04, 4.94506632e-04, 5.80347639e-04, 4.48511252e-04,
        0.00000000e+00, 3.98922508e-04, 6.83793170e-04, 4.86264885e-04]),
 'param_alpha': masked_array(data=[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 1, 1, 1, 1, 1, 1, 5, 5,
                    5, 5, 5, 5, 10, 10, 10, 10, 10, 10, 50, 50, 50, 50, 50,
                    50, 100, 100, 100, 100, 100, 100],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_l1_ratio': masked_array(data=[0.1, 0.5, 7, 0.95, 0.99, 1, 0.1, 0.5, 7, 0.95, 0.99, 1,
                    0.1, 0.5, 7, 0.95, 0.99, 1, 0.1, 0.5, 7, 0.95, 0.99, 1,
                    0.1, 0.5, 7, 0.95, 0.99, 1, 0.1, 0.5, 7, 0.95, 0.99, 1],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'alpha': 0.1, 'l1_ratio': 0.1},
  {'alpha': 0.1, 'l1_ratio': 0.5},
  {'alpha': 0.1, 'l1_ratio': 7},
  {'alpha': 0.1, 'l1_ratio': 0.95},
  {'alpha': 0.1, 'l1_ratio': 0.99},
  {'alpha': 0.1, 'l1_ratio': 1},
  {'alpha': 1, 'l1_ratio': 0.1},
  {'alpha': 1, 'l1_ratio': 0.5},
  {'alpha': 1, 'l1_ratio': 7},
  {'alpha': 1, 'l1_ratio': 0.95},
  {'alpha': 1, 'l1_ratio': 0.99},
  {'alpha': 1, 'l1_ratio': 1},
  {'alpha': 5, 'l1_ratio': 0.1},
  {'alpha': 5, 'l1_ratio': 0.5},
  {'alpha': 5, 'l1_ratio': 7},
  {'alpha': 5, 'l1_ratio': 0.95},
  {'alpha': 5, 'l1_ratio': 0.99},
  {'alpha': 5, 'l1_ratio': 1},
  {'alpha': 10, 'l1_ratio': 0.1},
  {'alpha': 10, 'l1_ratio': 0.5},
  {'alpha': 10, 'l1_ratio': 7},
  {'alpha': 10, 'l1_ratio': 0.95},
  {'alpha': 10, 'l1_ratio': 0.99},
  {'alpha': 10, 'l1_ratio': 1},
  {'alpha': 50, 'l1_ratio': 0.1},
  {'alpha': 50, 'l1_ratio': 0.5},
  {'alpha': 50, 'l1_ratio': 7},
  {'alpha': 50, 'l1_ratio': 0.95},
  {'alpha': 50, 'l1_ratio': 0.99},
  {'alpha': 50, 'l1_ratio': 1},
  {'alpha': 100, 'l1_ratio': 0.1},
  {'alpha': 100, 'l1_ratio': 0.5},
  {'alpha': 100, 'l1_ratio': 7},
  {'alpha': 100, 'l1_ratio': 0.95},
  {'alpha': 100, 'l1_ratio': 0.99},
  {'alpha': 100, 'l1_ratio': 1}],
 'split0_test_score': array([-6.95393042e+08, -6.82249724e+08,             nan, -6.67124193e+08,
        -6.73156095e+08, -6.81323292e+08, -8.91925838e+08, -7.99661410e+08,
                    nan, -6.82110706e+08, -6.66961790e+08, -6.79295965e+08,
        -1.55931531e+09, -1.21494349e+09,             nan, -7.38046922e+08,
        -6.81530386e+08, -6.72257245e+08, -2.19604890e+09, -1.63879390e+09,
                    nan, -7.99830330e+08, -6.97428030e+08, -6.67529479e+08,
        -4.52189848e+09, -3.61700533e+09,             nan, -1.21790944e+09,
        -8.01022072e+08, -6.53434547e+08, -5.42736230e+09, -4.67847612e+09,
                    nan, -1.64669386e+09, -9.18379808e+08, -6.52752184e+08]),
 'split1_test_score': array([-6.29642289e+08, -6.06455504e+08,             nan, -5.89427348e+08,
        -5.96251565e+08, -6.02953729e+08, -9.86013989e+08, -8.29868003e+08,
                    nan, -6.06423671e+08, -5.87901793e+08, -6.01334208e+08,
        -1.90863171e+09, -1.45899563e+09,             nan, -7.15203225e+08,
        -6.06314190e+08, -5.96927868e+08, -2.68077620e+09, -2.00832244e+09,
                    nan, -8.30888664e+08, -6.35662567e+08, -5.93305474e+08,
        -5.27454179e+09, -4.28926145e+09,             nan, -1.46432367e+09,
        -8.35789477e+08, -5.76699878e+08, -6.24404266e+09, -5.44328285e+09,
                    nan, -2.01957309e+09, -1.03391831e+09, -5.77442437e+08]),
 'split2_test_score': array([-3.82086109e+08, -3.80799127e+08,             nan, -3.82684120e+08,
        -3.82442733e+08, -3.82036308e+08, -4.70121284e+08, -4.17736935e+08,
                    nan, -3.80697563e+08, -3.81902369e+08, -3.81530240e+08,
        -9.76632756e+08, -7.01621253e+08,             nan, -3.91940846e+08,
        -3.80262886e+08, -3.80458767e+08, -1.51334948e+09, -1.04212856e+09,
                    nan, -4.17833776e+08, -3.81745666e+08, -3.80936777e+08,
        -3.58200089e+09, -2.76507806e+09,             nan, -7.04560560e+08,
        -4.18425363e+08, -3.80674995e+08, -4.40943405e+09, -3.72434980e+09,
                    nan, -1.04923091e+09, -4.88586336e+08, -3.76240086e+08]),
 'split3_test_score': array([-4.10903156e+08, -4.07180637e+08,             nan, -4.12422369e+08,
        -4.16325681e+08, -4.48372542e+08, -5.23202770e+08, -4.65862129e+08,
                    nan, -4.07007699e+08, -4.09370810e+08, -4.42026252e+08,
        -9.76046835e+08, -7.37032621e+08,             nan, -4.30543838e+08,
        -4.06250035e+08, -4.19806524e+08, -1.44061672e+09, -1.03257155e+09,
                    nan, -4.66096288e+08, -4.10707254e+08, -4.13362372e+08,
        -3.29524954e+09, -2.55135817e+09,             nan, -7.39564465e+08,
        -4.67159385e+08, -4.04728698e+08, -4.05974375e+09, -3.42600772e+09,
                    nan, -1.03870181e+09, -5.40992543e+08, -3.95064616e+08]),
 'split4_test_score': array([-5.93119366e+08, -5.88058690e+08,             nan, -5.89537810e+08,
        -5.92684453e+08, -6.04030495e+08, -7.75912759e+08, -6.83098083e+08,
                    nan, -5.87833439e+08, -5.88045870e+08, -6.00447822e+08,
        -1.47616988e+09, -1.11137341e+09,             nan, -6.24643219e+08,
        -5.86864849e+08, -5.91704694e+08, -2.15858691e+09, -1.56097258e+09,
                    nan, -6.82904123e+08, -5.93171026e+08, -5.89866974e+08,
        -4.63230364e+09, -3.67695209e+09,             nan, -1.11420369e+09,
        -6.82415913e+08, -5.80600135e+08, -5.57998123e+09, -4.79663576e+09,
                    nan, -1.56901053e+09, -8.01073268e+08, -5.72465292e+08]),
 'mean_test_score': array([-5.42228792e+08, -5.32948736e+08,             nan, -5.28239168e+08,
        -5.32172106e+08, -5.43743273e+08, -7.29435328e+08, -6.39245312e+08,
                    nan, -5.32814616e+08, -5.26836526e+08, -5.40926897e+08,
        -1.37935930e+09, -1.04479328e+09,             nan, -5.80075610e+08,
        -5.32244469e+08, -5.32231020e+08, -1.99787564e+09, -1.45655781e+09,
                    nan, -6.39510636e+08, -5.43742909e+08, -5.29000215e+08,
        -4.26119887e+09, -3.37993102e+09,             nan, -1.04811237e+09,
        -6.40962442e+08, -5.19227651e+08, -5.14411280e+09, -4.41375045e+09,
                    nan, -1.46464204e+09, -7.56590053e+08, -5.14792923e+08]),
 'std_test_score': array([1.23759734e+08, 1.18066299e+08,            nan, 1.10806471e+08,
        1.12679799e+08, 1.10736993e+08, 2.02075020e+08, 1.69186932e+08,
                   nan, 1.18069187e+08, 1.11278699e+08, 1.10929180e+08,
        3.59648538e+08, 2.88939876e+08,            nan, 1.43495728e+08,
        1.18092331e+08, 1.12253488e+08, 4.64059701e+08, 3.74185140e+08,
                   nan, 1.69365944e+08, 1.25262182e+08, 1.11646924e+08,
        7.24833073e+08, 6.38104178e+08,            nan, 2.89710411e+08,
        1.70308722e+08, 1.07133542e+08, 7.99458113e+08, 7.38583340e+08,
                   nan, 3.75759393e+08, 2.11364103e+08, 1.09376028e+08]),
 'rank_test_score': array([12, 10, 31,  4,  6, 14, 19, 16, 34,  9,  3, 11, 23, 21, 32, 15,  8,
         7, 26, 24, 36, 17, 13,  5, 28, 27, 33, 22, 18,  2, 30, 29, 35, 25,
        20,  1])}

In [51]:
pd.DataFrame(Grid_model.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_alpha,param_l1_ratio,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.115114,0.018965,0.001030,0.000055,0.1,0.1,"{'alpha': 0.1, 'l1_ratio': 0.1}",-6.953930e+08,-6.296423e+08,-3.820861e+08,-4.109032e+08,-5.931194e+08,-5.422288e+08,1.237597e+08,13
1,0.127593,0.003021,0.000799,0.000399,0.1,0.5,"{'alpha': 0.1, 'l1_ratio': 0.5}",-6.822497e+08,-6.064555e+08,-3.807991e+08,-4.071806e+08,-5.880587e+08,-5.329487e+08,1.180663e+08,10
2,0.002861,0.000455,0.000000,0.000000,0.1,7,"{'alpha': 0.1, 'l1_ratio': 7}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,35
3,0.358272,0.046906,0.001197,0.000235,0.1,0.95,"{'alpha': 0.1, 'l1_ratio': 0.95}",-6.671344e+08,-5.894025e+08,-3.827143e+08,-4.124198e+08,-5.896326e+08,-5.282607e+08,1.108094e+08,4
4,0.329248,0.041114,0.001248,0.000383,0.1,0.99,"{'alpha': 0.1, 'l1_ratio': 0.99}",-6.726844e+08,-5.963010e+08,-3.823734e+08,-4.166526e+08,-5.921745e+08,-5.320372e+08,1.124641e+08,7
5,0.334290,0.016892,0.001192,0.000400,0.1,1,"{'alpha': 0.1, 'l1_ratio': 1}",-6.782769e+08,-6.017437e+08,-3.828040e+08,-4.341237e+08,-5.958512e+08,-5.385599e+08,1.113213e+08,12
6,0.042879,0.007577,0.001017,0.000038,1,0.1,"{'alpha': 1, 'l1_ratio': 0.1}",-8.919258e+08,-9.860140e+08,-4.701213e+08,-5.232028e+08,-7.759128e+08,-7.294353e+08,2.020750e+08,19
7,0.047727,0.006892,0.001002,0.000009,1,0.5,"{'alpha': 1, 'l1_ratio': 0.5}",-7.996614e+08,-8.298680e+08,-4.177369e+08,-4.658621e+08,-6.830981e+08,-6.392453e+08,1.691869e+08,16
8,0.002351,0.000438,0.000000,0.000000,1,7,"{'alpha': 1, 'l1_ratio': 7}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,33
9,0.106607,0.009965,0.000876,0.000442,1,0.95,"{'alpha': 1, 'l1_ratio': 0.95}",-6.821107e+08,-6.064237e+08,-3.806976e+08,-4.070077e+08,-5.878334e+08,-5.328146e+08,1.180692e+08,9
10,0.278449,0.038756,0.000799,0.000399,1,0.99,"{'alpha': 1, 'l1_ratio': 0.99}",-6.669618e+08,-5.879018e+08,-3.819024e+08,-4.093708e+08,-5.880459e+08,-5.268365e+08,1.112787e+08,3
11,0.322895,0.043882,0.001178,0.000409,1,1,"{'alpha': 1, 'l1_ratio': 1}",-6.768547e+08,-6.003944e+08,-3.821751e+08,-4.306818e+08,-5.943141e+08,-5.368840e+08,1.114786e+08,11
12,0.018987,0.002232,0.000785,0.000394,5,0.1,"{'alpha': 5, 'l1_ratio': 0.1}",-1.559315e+09,-1.908632e+09,-9.766328e+08,-9.760468e+08,-1.476170e+09,-1.379359e+09,3.596485e+08,23
13,0.018952,0.002497,0.000797,0.000399,5,0.5,"{'alpha': 5, 'l1_ratio': 0.5}",-1.214943e+09,-1.458996e+09,-7.016213e+08,-7.370326e+08,-1.111373e+09,-1.044793e+09,2.889399e+08,21
14,0.003774,0.001172,0.000000,0.000000,5,7,"{'alpha': 5, 'l1_ratio': 7}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,32
15,0.049900,0.011052,0.000803,0.000401,5,0.95,"{'alpha': 5, 'l1_ratio': 0.95}",-7.380469e+08,-7.152032e+08,-3.919408e+08,-4.305438e+08,-6.246432e+08,-5.800756e+08,1.434957e+08,15
16,0.092646,0.016402,0.000818,0.000410,5,0.99,"{'alpha': 5, 'l1_ratio': 0.99}",-6.815304e+08,-6.063142e+08,-3.802629e+08,-4.062500e+08,-5.868648e+08,-5.322445e+08,1.180923e+08,8
17,0.298387,0.029496,0.001038,0.000629,5,1,"{'alpha': 5, 'l1_ratio': 1}",-6.714998e+08,-5.966434e+08,-3.804620e+08,-4.191734e+08,-5.913751e+08,-5.318307e+08,1.121230e+08,6
18,0.014297,0.002842,0.000815,0.000408,10,0.1,"{'alpha': 10, 'l1_ratio': 0.1}",-2.196049e+09,-2.680776e+09,-1.513349e+09,-1.440617e+09,-2.158587e+09,-1.997876e+09,4.640597e+08,26
19,0.014203,0.002037,0.000401,0.000491,10,0.5,"{'alpha': 10, 'l1_ratio': 0.5}",-1.638794e+09,-2.008322e+09,-1.042129e+09,-1.032572e+09,-1.560973e+09,-1.456558e+09,3.741851e+08,24
20,0.002030,0.000036,0.000000,0.000000,10,7,"{'alpha': 10, 'l1_ratio': 7}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,36
21,0.039940,0.009993,0.000602,0.000492,10,0.95,"{'alpha': 10, 'l1_ratio': 0.95}",-7.998303e+08,-8.308887e+08,-4.178338e+08,-4.660963e+08,-6.829041e+08,-6.395106e+08,1.693659e+08,17
22,0.046354,0.003799,0.000598,0.000488,10,0.99,"{'alpha': 10, 'l1_ratio': 0.99}",-6.974280e+08,-6.356626e+08,-3.817457e+08,-4.107073e+08,-5.931710e+08,-5.437429e+08,1.252622e+08,14
23,0.312083,0.020791,0.000937,0.000483,10,1,"{'alpha': 10, 'l1_ratio': 1}",-6.672342e+08,-5.937499e+08,-3.809313e+08,-4.127535e+08,-5.900095e+08,-5.289357e+08,1.117685e+08,5
24,0.015313,0.001282,0.001000,0.000009,50,0.1,"{'alpha': 50, 'l1_ratio': 0.1}",-4.521898e+09,-5.274542e+09,-3.582001e+09,-3.295250e+09,-4.632304e+09,-4.261199e+09,7.248331e+08,28
25,0.011928,0.001101,0.001060,0.000101,50,0.5,"{'alpha': 50, 'l1_ratio': 0.5}",-3.617005e+09,-4.289261e+09,-2.765078e+09,-2.551358e+09,-3.676952e+09,-3.379931e+09,6.381042e+08,27
26,0.002423,0.000480,0.000000,0.000000,50,7,"{'alpha': 50, 'l1_ratio': 7}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
27,0.017769,0.001515,0.000663,0.000555,50,0.95,"{'alpha': 50, 'l1_ratio': 0.95}",-1.217909e+09,-1.464324e+09,-7.045606e+08,-7.395645e+08,-1.114204e+09,-1.048112e+09,2.897104e+08,22
28,0.028363,0.001386,0.001017,0.000658,50,0.99,"{'alpha': 50, 'l1_ratio': 0.99}",-8.010221e+08,-8.357895e+08,-4.184254e+08,-4.671594e+08,-6.824159e+08,-6.409624e+08,1.703087e+08,18
29,0.243925,0.026061,0.000806,0.000403,50,1,"{'alpha': 50, 'l1_ratio': 1}",-6.534345e+08,-5.766999e+08,-3.806750e+08,-4.047287e+08,-5.806001e+08,-5.192277e+08,1.071335e+08,2
30,0.022654,0.002595,0.001425,0.000484,100,0.1,"{'alpha': 100, 'l1_ratio': 0.1}",-5.427362e+09,-6.244043e+09,-4.409434e+09,-4.059744e+09,-5.579981e+09,-5.144113e+09,7.994581e+08,30
31,0.015354,0.004298,0.001223,0.000393,100,0.5,"{'alpha': 100, 'l1_ratio': 0.5}",-4.678476e+09,-5.443283e+09,-3.724350e+09,-3.426008e+09,-4.796636e+09,-4.413750e+09,7.385833e+08,29
32,0.002788,0.000403,0.000000,0.000000,100,7,"{'alpha': 100, 'l1_ratio': 7}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,34
33,0.012475,0.001343,0.000917,0.000512,100,0.95,"{'alpha': 100, 'l1_ratio': 0.95}",-1.646694e+09,-2.019573e+09,-1.049231e+09,-1.038702e+09,-1.569011e+09,-1.464642e+09,3.757594e+08,25
34,0.023759,0.002931,0.001002,0.000004,100,0.99,"{'alpha': 100, 'l1_ratio': 0.99}",-9.183798e+08,-1.033918e+09,-4.885863e+08,-5.409925e+08,-8.010733e+08,-7.565901e+08,2.113641e+08,20
35,0.125946,0.009024,0.000647,0.000534,100,1,"{'alpha': 100, 'l1_ratio': 1}",-6.527522e+08,-5.774424e+08,-3.762401e+08,-3.950646e+08,-5.724653e+08,-5.147929e+08,1.093760e+08,1

In [35]:
y_pred=Grid_model.predict(scaled_X_test)

In [36]:
X_test

,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,Bsmt Unf SF,...,Sale Type_ConLw,Sale Type_New,Sale Type_Oth,Sale Type_VWD,Sale Type_WD,Sale Condition_AdjLand,Sale Condition_Alloca,Sale Condition_Family,Sale Condition_Normal,Sale Condition_Partial
1824,74.55102,6173,5,6,1967,1967,75.0,599.0,0.0,277.0,...,0,0,0,0,1,0,0,0,1,0
891,86.00000,13286,9,5,2007,2008,340.0,1234.0,0.0,464.0,...,0,0,0,0,1,0,0,0,1,0
1794,81.00000,10411,5,5,2007,2007,0.0,0.0,0.0,725.0,...,0,1,0,0,0,0,0,0,0,1
56,63.00000,8577,7,5,2004,2004,0.0,0.0,0.0,847.0,...,0,0,0,0,1,0,0,0,1,0
2847,60.00000,6000,5,5,1926,1950,0.0,0.0,0.0,1008.0,...,0,0,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1190,75.00000,9750,5,6,1965,1965,0.0,0.0,0.0,1625.0,...,0,0,0,0,0,0,0,0,1,0
1525,63.00000,15564,6,6,1914,1995,0.0,0.0,0.0,676.0,...,0,0,0,0,1,0,0,0,1,0
300,100.00000,15602,7,8,1959,1997,0.0,1247.0,0.0,254.0,...,0,0,0,0,1,0,0,0,1,0
321,89.00000,13214,9,5,2008,2009,0.0,0.0,0.0,2002.0,...,0,0,0,0,1,0,0,0,1,0
2146,70.00000,8749,7,5,2003,2003,0.0,654.0,0.0,325.0,...,0,0,0,0,1,0,0,0,1,0

In [37]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [38]:
mean_absolute_error(y_test,y_pred)

14195.354900562173

14149.055026374837

In [39]:
np.sqrt(mean_squared_error(y_test,y_pred))

20558.508566893164

In [41]:
mean_squared_error(y_test,y_pred)

422652274.4950197

In [42]:
MSE=mean_squared_error(y_test,y_pred)

In [43]:
RMSE = np.sqrt(MSE)
RMSE

20558.508566893164

20532.890234901013

In [44]:
np.mean(df["SalePrice"])

180815.53743589742

## Great work!

----